import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { videoId } = await req.json();

    if (!videoId) {
      throw new Error('Video ID is required');
    }

    console.log(`Fetching transcript for video: ${videoId}`);

    // First, get the video page to find available captions
    const videoPageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
    const videoPageHtml = await videoPageResponse.text();

    // Extract captions track URL from the page
    const captionsMatch = videoPageHtml.match(/"captionTracks":\s*\[(.*?)\]/);
    
    if (!captionsMatch) {
      console.log('No captions found in video page');
      return new Response(JSON.stringify({ 
        error: 'No captions available for this video',
        transcription: null 
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Parse the captions data
    const captionsData = JSON.parse(`[${captionsMatch[1]}]`);
    
    // Prefer Spanish captions, fallback to first available
    let captionTrack = captionsData.find((t: any) => 
      t.languageCode === 'es' || t.languageCode === 'es-419'
    ) || captionsData[0];

    if (!captionTrack || !captionTrack.baseUrl) {
      console.log('No caption track URL found');
      return new Response(JSON.stringify({ 
        error: 'No caption track found',
        transcription: null 
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Fetch the captions
    const captionsUrl = captionTrack.baseUrl.replace(/\\u0026/g, '&');
    console.log(`Fetching captions from: ${captionsUrl}`);
    
    const captionsResponse = await fetch(captionsUrl);
    const captionsXml = await captionsResponse.text();

    // Parse XML captions to extract text
    const textMatches = captionsXml.matchAll(/<text[^>]*>(.*?)<\/text>/g);
    const textSegments: string[] = [];
    
    for (const match of textMatches) {
      let text = match[1];
      // Decode HTML entities
      text = text
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/\n/g, ' ');
      textSegments.push(text);
    }

    const fullTranscription = textSegments.join(' ').trim();
    
    console.log(`Transcription extracted: ${fullTranscription.length} characters`);

    return new Response(JSON.stringify({ 
      transcription: fullTranscription,
      language: captionTrack.languageCode,
      isAutoGenerated: captionTrack.kind === 'asr'
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error fetching transcript:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error',
      transcription: null 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
