import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// YouTube API keys for fallback quota check
const YOUTUBE_API_KEYS = [
  'AIzaSyCDsT_d2qoAGah_eLgh0cW40CE0TRbGUJ0',
  'AIzaSyBfYt-z-o-TpYBAX-WBO6TSH1-xzRmy6gk'
];

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string };
}

interface TranscriptResult {
  transcription: string | null;
  language?: string;
  isAutoGenerated?: boolean;
  error?: string;
  errorCode?: string;
  availableLanguages?: string[];
}

// Method 1: Enhanced Innertube extraction from ytInitialPlayerResponse
async function tryInnertubeExtraction(videoId: string): Promise<TranscriptResult> {
  console.log(`[Method 1] Trying Innertube extraction for video: ${videoId}`);
  
  try {
    const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'es-ES,es;q=0.9,en;q=0.8',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      }
    });

    if (!response.ok) {
      return { transcription: null, error: 'Failed to fetch video page', errorCode: 'PAGE_FETCH_FAILED' };
    }

    const html = await response.text();

    // Try to extract ytInitialPlayerResponse (more reliable)
    const playerResponseMatch = html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
    
    if (!playerResponseMatch) {
      // Fallback to captionTracks regex
      const captionsMatch = html.match(/"captionTracks":\s*(\[.*?\])/);
      if (!captionsMatch) {
        console.log('[Method 1] No captions data found in page');
        return { transcription: null, error: 'No captions available', errorCode: 'NO_CAPTIONS' };
      }
      
      const captionTracks: CaptionTrack[] = JSON.parse(captionsMatch[1]);
      return await fetchCaptionsFromTracks(captionTracks);
    }

    const playerResponse = JSON.parse(playerResponseMatch[1]);
    const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks as CaptionTrack[] | undefined;

    if (!captionTracks || captionTracks.length === 0) {
      console.log('[Method 1] No caption tracks in player response');
      return { transcription: null, error: 'No captions available for this video', errorCode: 'NO_CAPTIONS' };
    }

    return await fetchCaptionsFromTracks(captionTracks);
  } catch (error) {
    console.error('[Method 1] Error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return { transcription: null, error: `Innertube extraction failed: ${message}`, errorCode: 'INNERTUBE_ERROR' };
  }
}

async function fetchCaptionsFromTracks(captionTracks: CaptionTrack[]): Promise<TranscriptResult> {
  const availableLanguages = captionTracks.map(t => t.languageCode);
  console.log(`Found ${captionTracks.length} caption tracks:`, availableLanguages);

  // Priority: Spanish manual > Spanish auto > any manual > any auto
  let captionTrack = captionTracks.find(t => 
    (t.languageCode === 'es' || t.languageCode === 'es-419' || t.languageCode === 'es-ES') && t.kind !== 'asr'
  );
  
  if (!captionTrack) {
    captionTrack = captionTracks.find(t => 
      t.languageCode === 'es' || t.languageCode === 'es-419' || t.languageCode === 'es-ES'
    );
  }
  
  if (!captionTrack) {
    captionTrack = captionTracks.find(t => t.kind !== 'asr');
  }
  
  if (!captionTrack) {
    captionTrack = captionTracks[0];
  }

  if (!captionTrack?.baseUrl) {
    return { 
      transcription: null, 
      error: 'No usable caption track found', 
      errorCode: 'NO_USABLE_TRACK',
      availableLanguages 
    };
  }

  // Fetch the captions XML
  const captionsUrl = captionTrack.baseUrl.replace(/\\u0026/g, '&');
  console.log(`Fetching captions from: ${captionsUrl.substring(0, 100)}...`);
  
  const captionsResponse = await fetch(captionsUrl);
  if (!captionsResponse.ok) {
    return { transcription: null, error: 'Failed to fetch captions file', errorCode: 'CAPTIONS_FETCH_FAILED' };
  }
  
  const captionsXml = await captionsResponse.text();
  const transcription = parseXmlCaptions(captionsXml);

  if (!transcription) {
    return { transcription: null, error: 'Failed to parse captions', errorCode: 'PARSE_FAILED' };
  }

  return { 
    transcription,
    language: captionTrack.languageCode,
    isAutoGenerated: captionTrack.kind === 'asr',
    availableLanguages
  };
}

// Method 2: Direct Timedtext API
async function tryTimedtextApi(videoId: string): Promise<TranscriptResult> {
  console.log(`[Method 2] Trying Timedtext API for video: ${videoId}`);
  
  const languages = ['es', 'es-419', 'es-ES', 'en'];
  
  for (const lang of languages) {
    try {
      // Try srv3 format (JSON-like)
      const url = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${lang}&fmt=srv3`;
      console.log(`Trying timedtext URL: ${url}`);
      
      const response = await fetch(url, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        }
      });
      
      if (response.ok) {
        const text = await response.text();
        if (text && text.length > 50) {
          const transcription = parseXmlCaptions(text);
          if (transcription && transcription.length > 50) {
            console.log(`[Method 2] Success with language: ${lang}`);
            return { 
              transcription, 
              language: lang,
              isAutoGenerated: false
            };
          }
        }
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.log(`[Method 2] Failed for ${lang}:`, message);
    }
  }
  
  return { transcription: null, error: 'Timedtext API returned no results', errorCode: 'TIMEDTEXT_FAILED' };
}

// Method 3: YouTube Data API check (to provide better error messages)
async function checkCaptionsWithYouTubeApi(videoId: string): Promise<{ hasCaptions: boolean; languages: string[]; error?: string }> {
  console.log(`[Method 3] Checking captions via YouTube Data API for video: ${videoId}`);
  
  for (const apiKey of YOUTUBE_API_KEYS) {
    try {
      const url = `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${videoId}&key=${apiKey}`;
      const response = await fetch(url);
      
      if (response.status === 403) {
        console.log('[Method 3] API quota exceeded, trying next key');
        continue;
      }
      
      if (!response.ok) {
        const errorData = await response.json();
        console.log('[Method 3] API error:', errorData);
        continue;
      }
      
      const data = await response.json();
      const items = data.items || [];
      const languages = items.map((item: any) => item.snippet?.language).filter(Boolean);
      
      return { hasCaptions: items.length > 0, languages };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.log('[Method 3] Error with API key:', message);
    }
  }
  
  return { hasCaptions: false, languages: [], error: 'Could not verify caption availability' };
}

function parseXmlCaptions(xml: string): string {
  const textMatches = xml.matchAll(/<text[^>]*>(.*?)<\/text>/gs);
  const textSegments: string[] = [];
  
  for (const match of textMatches) {
    let text = match[1];
    // Decode HTML entities
    text = text
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&apos;/g, "'")
      .replace(/<[^>]+>/g, '') // Remove any nested tags
      .replace(/\n/g, ' ')
      .trim();
    if (text) textSegments.push(text);
  }
  
  return textSegments.join(' ').trim();
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { videoId } = await req.json();

    if (!videoId) {
      return new Response(JSON.stringify({ 
        error: 'Video ID is required',
        errorCode: 'MISSING_VIDEO_ID'
      }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log(`\n========== Fetching transcript for video: ${videoId} ==========\n`);

    // Try Method 1: Innertube extraction
    let result = await tryInnertubeExtraction(videoId);
    
    if (result.transcription) {
      console.log(`[Success] Method 1 - Innertube: ${result.transcription.length} characters`);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    
    console.log(`[Method 1 failed] ${result.error}`);

    // Try Method 2: Timedtext API
    result = await tryTimedtextApi(videoId);
    
    if (result.transcription) {
      console.log(`[Success] Method 2 - Timedtext: ${result.transcription.length} characters`);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    
    console.log(`[Method 2 failed] ${result.error}`);

    // Method 3: Check with YouTube API for better error message
    const apiCheck = await checkCaptionsWithYouTubeApi(videoId);
    
    let errorMessage: string;
    let errorCode: string;
    
    if (apiCheck.hasCaptions && apiCheck.languages.length > 0) {
      errorMessage = `This video has captions in ${apiCheck.languages.join(', ')} but they couldn't be fetched. The owner may have restricted access.`;
      errorCode = 'CAPTIONS_RESTRICTED';
    } else if (apiCheck.error) {
      errorMessage = 'Could not fetch captions. The video may not have captions enabled, or they may still be processing.';
      errorCode = 'CAPTIONS_UNAVAILABLE';
    } else {
      errorMessage = 'This video does not have captions available. It may be too new - captions can take up to 24 hours to be generated.';
      errorCode = 'NO_CAPTIONS';
    }

    console.log(`[Final result] No transcription available: ${errorCode}`);
    
    return new Response(JSON.stringify({ 
      transcription: null,
      error: errorMessage,
      errorCode,
      availableLanguages: apiCheck.languages
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error fetching transcript:', error);
    return new Response(JSON.stringify({ 
      transcription: null,
      error: error instanceof Error ? error.message : 'Unknown error',
      errorCode: 'UNKNOWN_ERROR'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
