import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string };
}

interface TranscriptResult {
  transcription: string | null;
  language?: string;
  isAutoGenerated?: boolean;
  error?: string;
  errorCode?: string;
  availableLanguages?: string[];
  tier?: 'youtube' | 'assemblyai';
}

// ==================== TIER 1: YouTube Captions (Free) ====================

async function tryInnertubeExtraction(videoId: string): Promise<TranscriptResult> {
  console.log(`[Tier 1] Trying YouTube captions for video: ${videoId}`);
  
  try {
    const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'es-ES,es;q=0.9,en;q=0.8',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Cookie': '',
      }
    });

    if (!response.ok) {
      return { transcription: null, error: 'Failed to fetch video page', errorCode: 'PAGE_FETCH_FAILED' };
    }

    const html = await response.text();
    const playerResponseMatch = html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
    
    if (!playerResponseMatch) {
      console.log('[Tier 1] No ytInitialPlayerResponse found');
      return { transcription: null, error: 'No player response found', errorCode: 'NO_PLAYER_RESPONSE' };
    }

    const playerResponse = JSON.parse(playerResponseMatch[1]);
    const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks as CaptionTrack[] | undefined;

    if (!captionTracks || captionTracks.length === 0) {
      console.log('[Tier 1] No caption tracks in player response');
      return { transcription: null, error: 'No captions available for this video', errorCode: 'NO_CAPTIONS' };
    }

    const availableLanguages = captionTracks.map(t => t.languageCode);
    console.log(`[Tier 1] Found ${captionTracks.length} tracks:`, JSON.stringify(availableLanguages));

    return await fetchCaptionsFromTracks(captionTracks);
  } catch (error) {
    console.error('[Tier 1] Error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return { transcription: null, error: `Innertube extraction failed: ${message}`, errorCode: 'INNERTUBE_ERROR' };
  }
}

async function fetchCaptionsFromTracks(captionTracks: CaptionTrack[]): Promise<TranscriptResult> {
  const availableLanguages = captionTracks.map(t => t.languageCode);

  // Priority: Spanish manual > Spanish auto > any manual > any auto
  let captionTrack = captionTracks.find(t => 
    (t.languageCode === 'es' || t.languageCode === 'es-419' || t.languageCode === 'es-ES') && t.kind !== 'asr'
  );
  
  if (!captionTrack) {
    captionTrack = captionTracks.find(t => 
      t.languageCode === 'es' || t.languageCode === 'es-419' || t.languageCode === 'es-ES'
    );
  }
  
  if (!captionTrack) {
    captionTrack = captionTracks.find(t => t.kind !== 'asr');
  }
  
  if (!captionTrack) {
    captionTrack = captionTracks[0];
  }

  console.log(`[Tier 1] Selected track: lang=${captionTrack?.languageCode}, kind=${captionTrack?.kind || 'manual'}`);

  if (!captionTrack?.baseUrl) {
    console.log('[Tier 1] No baseUrl in track');
    return { 
      transcription: null, 
      error: 'No usable caption track found (missing baseUrl)', 
      errorCode: 'NO_USABLE_TRACK',
      availableLanguages 
    };
  }

  // Decode the URL properly
  let captionsUrl = captionTrack.baseUrl;
  const unicodeEscapes: Record<string, string> = {
    '\\u0026': '&', '\\u003d': '=', '\\u003c': '<', '\\u003e': '>',
    '\\u0027': "'", '\\u0022': '"', '\\u002f': '/'
  };
  
  for (const [escape, char] of Object.entries(unicodeEscapes)) {
    captionsUrl = captionsUrl.split(escape).join(char);
  }
  
  try {
    captionsUrl = JSON.parse(`"${captionsUrl.replace(/"/g, '\\"')}"`);
  } catch {
    // URL wasn't JSON-encoded
  }
  
  console.log(`[Tier 1] Fetching: ${captionsUrl.substring(0, 150)}...`);
  
  try {
    const captionsResponse = await fetch(captionsUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': '*/*',
        'Accept-Language': 'es-ES,es;q=0.9,en;q=0.8',
        'Referer': 'https://www.youtube.com/',
        'Origin': 'https://www.youtube.com',
      }
    });
    
    if (!captionsResponse.ok) {
      console.log(`[Tier 1] Caption fetch failed: ${captionsResponse.status}`);
      return { transcription: null, error: `Caption fetch failed: ${captionsResponse.status}`, errorCode: 'CAPTIONS_FETCH_FAILED' };
    }
    
    const captionsText = await captionsResponse.text();
    console.log(`[Tier 1] Received ${captionsText.length} bytes`);
    
    if (captionsText.length < 50) {
      console.log(`[Tier 1] Response too short: "${captionsText.substring(0, 100)}"`);
      return { transcription: null, error: 'Caption response empty', errorCode: 'CAPTIONS_EMPTY' };
    }
    
    // Try XML parsing first
    let transcription = parseXmlCaptions(captionsText);
    
    // If XML parsing fails, try JSON format
    if (!transcription || transcription.length < 20) {
      console.log('[Tier 1] XML parsing yielded no results, trying JSON...');
      try {
        const jsonData = JSON.parse(captionsText);
        if (jsonData.events) {
          transcription = jsonData.events
            .filter((e: any) => e.segs)
            .map((e: any) => e.segs.map((s: any) => s.utf8).join(''))
            .join(' ')
            .replace(/\s+/g, ' ')
            .trim();
        }
      } catch {
        // Not JSON either
      }
    }

    if (!transcription || transcription.length < 20) {
      console.log(`[Tier 1] Could not parse captions. First 300 chars: ${captionsText.substring(0, 300)}`);
      return { transcription: null, error: 'Failed to parse caption content', errorCode: 'PARSE_FAILED' };
    }

    console.log(`[Tier 1] Success: ${transcription.length} characters`);
    return { 
      transcription,
      language: captionTrack.languageCode,
      isAutoGenerated: captionTrack.kind === 'asr',
      availableLanguages,
      tier: 'youtube'
    };
  } catch (error) {
    console.error('[Tier 1] Fetch error:', error);
    return { transcription: null, error: `Fetch error: ${error instanceof Error ? error.message : 'Unknown'}`, errorCode: 'CAPTIONS_FETCH_ERROR' };
  }
}

async function tryTimedtextApi(videoId: string): Promise<TranscriptResult> {
  console.log(`[Tier 1b] Trying Timedtext API for video: ${videoId}`);
  
  const languages = ['es', 'es-419', 'es-ES', 'en'];
  
  for (const lang of languages) {
    try {
      for (const fmt of ['srv1', 'srv3']) {
        const url = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${lang}&fmt=${fmt}`;
        const response = await fetch(url, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': '*/*',
            'Accept-Language': 'es-ES,es;q=0.9',
          }
        });
        
        if (response.ok) {
          const text = await response.text();
          if (text && text.length > 50) {
            let transcription: string | null = null;
            
            if (fmt === 'srv3') {
              try {
                const data = JSON.parse(text);
                if (data.events) {
                  transcription = data.events
                    .filter((e: any) => e.segs)
                    .map((e: any) => e.segs.map((s: any) => s.utf8).join(''))
                    .join(' ')
                    .replace(/\s+/g, ' ')
                    .trim();
                }
              } catch {
                transcription = parseXmlCaptions(text);
              }
            } else {
              transcription = parseXmlCaptions(text);
            }
            
            if (transcription && transcription.length > 50) {
              console.log(`[Tier 1b] Success with ${lang} (${fmt}): ${transcription.length} chars`);
              return { 
                transcription, 
                language: lang,
                isAutoGenerated: false,
                tier: 'youtube'
              };
            }
          }
        }
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.log(`[Tier 1b] Failed for ${lang}:`, message);
    }
  }
  
  return { transcription: null, error: 'Timedtext API returned no results', errorCode: 'TIMEDTEXT_FAILED' };
}

// ==================== Audio Download ====================

const PIPED_INSTANCES = [
  'https://pipedapi.kavin.rocks',
  'https://pipedapi.adminforge.de',
  'https://api.piped.yt',
  'https://pipedapi.r4fo.com',
  'https://pipedapi.darkness.services',
  'https://pipedapi.in.projectsegfau.lt',
  'https://pipedapi.leptons.xyz',
  'https://pipedapi.moomoo.me',
  'https://pipedapi.syncpundit.io',
  'https://pipedapi.privacydev.net',
  'https://pipedapi.smnz.de',
];

const INVIDIOUS_INSTANCES = [
  'https://inv.nadeko.net',
  'https://invidious.nerdvpn.de',
  'https://invidious.protokolla.fi',
  'https://inv.tux.pizza',
  'https://invidious.privacyredirect.com',
  'https://yewtu.be',
  'https://vid.puffyan.us',
  'https://invidious.lunar.icu',
  'https://invidious.drgns.space',
];

async function downloadAudioWithPiped(videoId: string): Promise<{ audioBuffer: ArrayBuffer; durationMinutes: number } | null> {
  console.log(`[Piped] Attempting audio download for: ${videoId}`);
  
  for (const instance of PIPED_INSTANCES) {
    try {
      console.log(`[Piped] Trying instance: ${instance}`);
      
      const infoResponse = await fetch(`${instance}/streams/${videoId}`, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
          'Accept': 'application/json'
        },
        signal: AbortSignal.timeout(15000)
      });
      
      if (!infoResponse.ok) {
        console.log(`[Piped] ${instance} returned ${infoResponse.status}`);
        continue;
      }
      
      const data = await infoResponse.json();
      
      if (data.error) {
        console.log(`[Piped] ${instance} error: ${data.error}`);
        continue;
      }
      
      const durationMinutes = (data.duration || 0) / 60;
      console.log(`[Piped] Video duration: ${durationMinutes.toFixed(1)} minutes`);
      
      // Find audio streams
      const audioStreams = (data.audioStreams || [])
        .filter((s: any) => s.url && s.mimeType?.includes('audio'))
        .sort((a: any, b: any) => (a.bitrate || 0) - (b.bitrate || 0));
      
      if (audioStreams.length === 0) {
        console.log(`[Piped] No audio streams from ${instance}`);
        continue;
      }
      
      console.log(`[Piped] Found ${audioStreams.length} audio streams`);
      
      for (const stream of audioStreams) {
        console.log(`[Piped] Trying stream: ${stream.mimeType}, ${stream.bitrate}bps`);
        
        try {
          const audioResponse = await fetch(stream.url, {
            headers: {
              'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
              'Accept': '*/*',
            },
            signal: AbortSignal.timeout(180000)
          });
          
          if (!audioResponse.ok) {
            console.log(`[Piped] Stream download failed: ${audioResponse.status}`);
            continue;
          }
          
          const audioBuffer = await audioResponse.arrayBuffer();
          
          if (audioBuffer.byteLength < 10000) {
            console.log(`[Piped] Audio too small: ${audioBuffer.byteLength} bytes`);
            continue;
          }
          
          console.log(`[Piped] Success: ${(audioBuffer.byteLength / 1024 / 1024).toFixed(2)} MB`);
          return { audioBuffer, durationMinutes };
          
        } catch (streamError) {
          const msg = streamError instanceof Error ? streamError.message : 'Unknown';
          console.log(`[Piped] Stream download error: ${msg}`);
          continue;
        }
      }
      
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown';
      console.log(`[Piped] ${instance} failed: ${msg}`);
      continue;
    }
  }
  
  console.log('[Piped] All instances failed');
  return null;
}

async function downloadAudioFromYouTubeDirect(videoId: string): Promise<{ audioBuffer: ArrayBuffer; durationMinutes: number } | null> {
  console.log(`[YouTube Direct] Attempting audio extraction for: ${videoId}`);
  
  try {
    const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const response = await fetch(watchUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9,es;q=0.8',
        'Cache-Control': 'no-cache',
      }
    });

    if (!response.ok) {
      console.log(`[YouTube Direct] Failed to fetch page: ${response.status}`);
      return null;
    }

    const html = await response.text();
    const playerResponseMatch = html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
    if (!playerResponseMatch) {
      console.log('[YouTube Direct] No ytInitialPlayerResponse found');
      return null;
    }

    const playerResponse = JSON.parse(playerResponseMatch[1]);
    const playability = playerResponse?.playabilityStatus;
    if (playability?.status !== 'OK') {
      console.log(`[YouTube Direct] Video not playable: ${playability?.status}`);
      return null;
    }

    const durationSeconds = parseInt(playerResponse?.videoDetails?.lengthSeconds || '0');
    const durationMinutes = durationSeconds / 60;
    console.log(`[YouTube Direct] Video duration: ${durationMinutes.toFixed(1)} minutes`);

    const streamingData = playerResponse?.streamingData;
    if (!streamingData) {
      console.log('[YouTube Direct] No streaming data found');
      return null;
    }

    const adaptiveFormats = streamingData.adaptiveFormats || [];
    const audioFormats = adaptiveFormats
      .filter((f: any) => f.mimeType?.startsWith('audio/') && f.url)
      .sort((a: any, b: any) => (a.bitrate || 0) - (b.bitrate || 0));

    if (audioFormats.length === 0) {
      console.log('[YouTube Direct] No audio formats available');
      return null;
    }

    for (const format of audioFormats) {
      console.log(`[YouTube Direct] Trying format: ${format.mimeType}, ${format.bitrate}bps`);

      try {
        const audioResponse = await fetch(format.url, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': '*/*',
            'Accept-Encoding': 'identity',
            'Range': 'bytes=0-',
            'Referer': 'https://www.youtube.com/',
            'Origin': 'https://www.youtube.com',
          },
          signal: AbortSignal.timeout(180000)
        });

        if (!audioResponse.ok) {
          console.log(`[YouTube Direct] Audio fetch failed: ${audioResponse.status}`);
          continue;
        }

        const audioBuffer = await audioResponse.arrayBuffer();
        
        if (audioBuffer.byteLength < 10000) {
          console.log(`[YouTube Direct] Audio too small (${audioBuffer.byteLength} bytes)`);
          continue;
        }

        console.log(`[YouTube Direct] Success: ${(audioBuffer.byteLength / 1024 / 1024).toFixed(2)} MB`);
        return { audioBuffer, durationMinutes };

      } catch (error) {
        const msg = error instanceof Error ? error.message : 'Unknown';
        console.log(`[YouTube Direct] Format download failed: ${msg}`);
        continue;
      }
    }

    console.log('[YouTube Direct] All formats failed');
    return null;

  } catch (error) {
    console.error('[YouTube Direct] Error:', error instanceof Error ? error.message : error);
    return null;
  }
}

async function downloadAudioWithInvidious(videoId: string): Promise<{ audioBuffer: ArrayBuffer; durationMinutes: number } | null> {
  console.log(`[Invidious] Attempting audio download for: ${videoId}`);
  
  for (const instance of INVIDIOUS_INSTANCES) {
    try {
      console.log(`[Invidious] Trying instance: ${instance}`);
      
      const infoResponse = await fetch(`${instance}/api/v1/videos/${videoId}`, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
          'Accept': 'application/json'
        },
        signal: AbortSignal.timeout(15000)
      });
      
      if (!infoResponse.ok) {
        console.log(`[Invidious] ${instance} returned ${infoResponse.status}`);
        continue;
      }
      
      const data = await infoResponse.json();
      const durationMinutes = (data.lengthSeconds || 0) / 60;
      
      const audioFormats = data.adaptiveFormats?.filter((f: any) => 
        f.type?.startsWith('audio/') && f.url
      ) || [];
      
      if (audioFormats.length === 0) {
        console.log(`[Invidious] No audio formats from ${instance}`);
        continue;
      }
      
      audioFormats.sort((a: any, b: any) => (a.bitrate || 0) - (b.bitrate || 0));
      const audioFormat = audioFormats[0];
      
      console.log(`[Invidious] Trying format: ${audioFormat.type}, ${audioFormat.bitrate}bps`);
      
      const audioResponse = await fetch(audioFormat.url, {
        headers: { 'User-Agent': 'Mozilla/5.0' },
        signal: AbortSignal.timeout(180000)
      });
      
      if (!audioResponse.ok) {
        console.log(`[Invidious] Audio fetch failed: ${audioResponse.status}`);
        continue;
      }
      
      const audioBuffer = await audioResponse.arrayBuffer();
      if (audioBuffer.byteLength < 10000) {
        console.log(`[Invidious] Audio too small: ${audioBuffer.byteLength} bytes`);
        continue;
      }
      
      console.log(`[Invidious] Success from ${instance}: ${(audioBuffer.byteLength / 1024 / 1024).toFixed(2)} MB`);
      return { audioBuffer, durationMinutes };
      
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown';
      console.log(`[Invidious] ${instance} failed: ${message}`);
      continue;
    }
  }
  
  console.log('[Invidious] All instances failed');
  return null;
}

async function downloadAudioFromYouTube(videoId: string): Promise<{ audioBuffer: ArrayBuffer; durationMinutes: number } | null> {
  console.log(`[Audio Download] Starting for video: ${videoId}`);
  
  // Method 1: Piped API
  const pipedResult = await downloadAudioWithPiped(videoId);
  if (pipedResult) {
    console.log('[Audio Download] Success with Piped');
    return pipedResult;
  }
  
  // Method 2: Invidious API
  console.log('[Audio Download] Piped failed, trying Invidious...');
  const invResult = await downloadAudioWithInvidious(videoId);
  if (invResult) {
    console.log('[Audio Download] Success with Invidious');
    return invResult;
  }
  
  // Method 3: Direct YouTube extraction (often rate-limited)
  console.log('[Audio Download] Invidious failed, trying YouTube Direct...');
  const directResult = await downloadAudioFromYouTubeDirect(videoId);
  if (directResult) {
    console.log('[Audio Download] Success with YouTube Direct');
    return directResult;
  }
  
  console.log('[Audio Download] All download methods failed');
  return null;
}

// ==================== TIER 2: AssemblyAI ====================

async function tryAssemblyAI(videoId: string): Promise<TranscriptResult> {
  const assemblyApiKey = Deno.env.get('ASSEMBLYAI_API_KEY');
  
  if (!assemblyApiKey) {
    console.log('[Tier 2] AssemblyAI API key not configured');
    return { transcription: null, error: 'AssemblyAI not configured', errorCode: 'ASSEMBLYAI_NOT_CONFIGURED' };
  }

  console.log('[Tier 2] AssemblyAI - Starting transcription process...');

  // Step 1: Download audio
  const audioData = await downloadAudioFromYouTube(videoId);
  if (!audioData) {
    return { transcription: null, error: 'Failed to download audio', errorCode: 'AUDIO_DOWNLOAD_FAILED' };
  }

  console.log(`[Tier 2] Audio downloaded: ${(audioData.audioBuffer.byteLength / 1024 / 1024).toFixed(2)} MB, ${audioData.durationMinutes.toFixed(1)} min`);

  // Step 2: Upload audio to AssemblyAI
  console.log('[Tier 2] Uploading audio to AssemblyAI...');
  
  try {
    const uploadResponse = await fetch('https://api.assemblyai.com/v2/upload', {
      method: 'POST',
      headers: {
        'Authorization': assemblyApiKey,
        'Content-Type': 'application/octet-stream'
      },
      body: audioData.audioBuffer
    });

    if (!uploadResponse.ok) {
      const errorText = await uploadResponse.text();
      console.error('[Tier 2] AssemblyAI upload failed:', uploadResponse.status, errorText);
      return { transcription: null, error: `AssemblyAI upload failed: ${uploadResponse.status}`, errorCode: 'ASSEMBLYAI_UPLOAD_FAILED' };
    }

    const uploadResult = await uploadResponse.json();
    const uploadUrl = uploadResult.upload_url;
    console.log('[Tier 2] Audio uploaded successfully');

    // Step 3: Create transcription job
    console.log('[Tier 2] Creating transcription job...');
    
    const transcriptResponse = await fetch('https://api.assemblyai.com/v2/transcript', {
      method: 'POST',
      headers: {
        'Authorization': assemblyApiKey,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        audio_url: uploadUrl,
        language_code: 'es' // Spanish
      })
    });

    if (!transcriptResponse.ok) {
      const errorText = await transcriptResponse.text();
      console.error('[Tier 2] AssemblyAI transcript creation failed:', errorText);
      return { transcription: null, error: `AssemblyAI transcript creation failed`, errorCode: 'ASSEMBLYAI_CREATE_FAILED' };
    }

    const transcriptJob = await transcriptResponse.json();
    const transcriptId = transcriptJob.id;
    console.log(`[Tier 2] Transcription job created: ${transcriptId}`);

    // Step 4: Poll for completion
    console.log('[Tier 2] Polling for completion...');
    
    const maxAttempts = 120; // 10 minutes max (5s intervals)
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      await new Promise(resolve => setTimeout(resolve, 5000)); // Wait 5 seconds
      
      const statusResponse = await fetch(`https://api.assemblyai.com/v2/transcript/${transcriptId}`, {
        headers: {
          'Authorization': assemblyApiKey
        }
      });

      if (!statusResponse.ok) {
        console.log(`[Tier 2] Status check failed: ${statusResponse.status}`);
        continue;
      }

      const statusResult = await statusResponse.json();
      console.log(`[Tier 2] Status: ${statusResult.status} (attempt ${attempt + 1})`);

      if (statusResult.status === 'completed') {
        const transcription = statusResult.text;
        
        if (!transcription || transcription.length < 20) {
          return { transcription: null, error: 'AssemblyAI returned empty result', errorCode: 'ASSEMBLYAI_EMPTY_RESULT' };
        }

        console.log(`[Tier 2] Success: ${transcription.length} characters`);
        return { 
          transcription,
          language: 'es',
          isAutoGenerated: false,
          tier: 'assemblyai'
        };
      }

      if (statusResult.status === 'error') {
        console.error('[Tier 2] AssemblyAI transcription error:', statusResult.error);
        return { transcription: null, error: `AssemblyAI error: ${statusResult.error}`, errorCode: 'ASSEMBLYAI_ERROR' };
      }
    }

    return { transcription: null, error: 'AssemblyAI transcription timed out', errorCode: 'ASSEMBLYAI_TIMEOUT' };

  } catch (error) {
    console.error('[Tier 2] AssemblyAI error:', error);
    return { transcription: null, error: `AssemblyAI failed: ${error instanceof Error ? error.message : 'Unknown'}`, errorCode: 'ASSEMBLYAI_ERROR' };
  }
}

// ==================== Utilities ====================

function parseXmlCaptions(xml: string): string {
  const textMatches = xml.matchAll(/<text[^>]*>(.*?)<\/text>/gs);
  const textSegments: string[] = [];
  
  for (const match of textMatches) {
    let text = match[1];
    text = text
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&apos;/g, "'")
      .replace(/<[^>]+>/g, '')
      .replace(/\n/g, ' ')
      .trim();
    if (text) textSegments.push(text);
  }
  
  return textSegments.join(' ').trim();
}

// ==================== Main Handler ====================

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { videoId } = await req.json();

    if (!videoId) {
      return new Response(JSON.stringify({ 
        error: 'Video ID is required',
        errorCode: 'MISSING_VIDEO_ID'
      }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log(`\n========== Fetching transcript for video: ${videoId} ==========\n`);

    let result: TranscriptResult;

    // TIER 1: YouTube Captions (Free, unlimited)
    result = await tryInnertubeExtraction(videoId);
    if (result.transcription) {
      console.log(`[Success] Tier 1 - YouTube captions: ${result.transcription.length} characters`);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    console.log(`[Tier 1 failed] ${result.error}`);

    // Tier 1b: Timedtext API fallback
    result = await tryTimedtextApi(videoId);
    if (result.transcription) {
      console.log(`[Success] Tier 1b - Timedtext: ${result.transcription.length} characters`);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    console.log(`[Tier 1b failed] ${result.error}`);

    // TIER 2: AssemblyAI (Paid, reliable)
    result = await tryAssemblyAI(videoId);
    if (result.transcription) {
      console.log(`[Success] Tier 2 - AssemblyAI: ${result.transcription.length} characters`);
      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    console.log(`[Tier 2 failed] ${result.error}`);

    // All methods failed
    console.log(`[All methods failed]`);
    return new Response(JSON.stringify({
      transcription: null,
      error: 'All transcription methods failed. The video may not have captions and audio download was unsuccessful.',
      errorCode: 'ALL_METHODS_FAILED'
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Handler error:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error',
      errorCode: 'HANDLER_ERROR'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
